# Generated by Django 6.0.5 on 2026-05-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfigurations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_before_expired_in_days', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_per_day', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('alert_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('time_gap_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertconfigurations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlertTemplates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('to_whom', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert_templates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAdjustments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_adjustments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerUpdate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_updated', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_update',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentDispatchLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dispatchable_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatchable_id', models.BigIntegerField(blank=True, null=True)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_by', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_dispatch_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailApiTokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mail_driver', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_host', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_port', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_username', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_password', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_encryption', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emailapitokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emailfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'emaillogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceAdvanceSettlements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'invoiceadvancesettlements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('permission_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_view_menu', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenusVersions2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('permission_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_view_menu', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menus_versions2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAudits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questionnaire_audits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireModules',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_id', models.BigIntegerField(blank=True, null=True)),
                ('module_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questionnaire_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('module_type', models.CharField(blank=True, max_length=255, null=True)),
                ('module_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questionnaires',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleHasMenus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_has_menus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmsApiTokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('identity', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sms_api_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmsLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('alert_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sms_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='roleshaspermissions',
            table='role_has_permissions',
        ),
    ]
